# Site settings
title: Alassane.co
email: alassanedialdiop@gmail.com
description: >- 
  Alassane Diop - Data Scientist & AI Consultant specializing in machine learning, 
  recommendation systems, and predictive analytics. Based in Montreal, Quebec.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alassane.ai" # your custom domain

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"